### ISSUE TITLE
short_open_tag problem

### ISSUE THREAD

**Issue by Jirido** [YuriyNasretdinov/Dolphin.php#2]
Hi. Yuriy. First i want to thank you  for your fine coding. I love old dolphine and is hot to try the new bugfixed one (well anyway) 
While  trying to load Dolphine it seem to miss a friendly session handler.
When running phpinfo it shows that memcached is registered as such.. 
Im not good with this stuff at all but just really like Dolphine and have used it for many years..
So now on this new server with fpmphp, pools and all..
Anyway!
Here is a phpinfo http://wikisend.com/download/499290/phpinfo.htm 
and Dolphine's output http://wikisend.com/download/157302/boing.htm
If you could give me any advice it would be so much appreciated.
Thanks.  David.

**Comment by YuriyNasretdinov** [comment]
Hello, David. Could you please upload the output to something like gist or other service that does not require you to wait to see file and to click suspicious links?

**Comment by Jirido** [comment]
Hi. Sorry for that. I guess gist present htm raw so i thought to try to find some that show html but it came to be wikisend.. but at least it woun't make you wait and give you straight htm files, no fuzz.  
Here is phpinfo http://wikisend.com/download/499290/phpinfo.htm
and Dolphine's output http://wikisend.com/download/157302/boing.htm

**Comment by YuriyNasretdinov** [comment]
Please just upload the html source code anywhere, I can open it in browser myself

**Comment by Jirido** [comment]
Right You hacker aware man :)  I also try to be!    Gist it will be!
phpinfo.htm https://gist.github.com/Jirido/ecaffe85df8a8b8c01167c61e040789a
Dolphine output https://gist.github.com/Jirido/88b58d48b6bff2eb963387b24d48e5e9

**Comment by YuriyNasretdinov** [comment]
So what I can see from the output you have a very strange web server that somehow affects script output. But the reason why my code does not work is probably due to the fact that you have short_open_tag is set to Off in your PHP config. This project is very old so it does not take the fact that short_open_tag is off by default for many years :).

**Comment by Jirido** [comment]
The only strange i know of is running in a pool.. :) I tried to change the tag in index.php but i guess i should do it in all files right? an recursive search and replace of <? to <?php  
Ill feed the dog and then try. I come back to you if i suceed. els i guess i have to try and turn on the shorthand and see what happens with my joomla site that is heavy with xml.. : / or maybe it can be set in .htaccess..

**Comment by Jirido** [comment]
Well Hi again. 
I tried desperatly to make a "php_admin_value short_open_tag 1 or on" work on my Dolphine subfolder(in a Joomla root) true local php.ini(in the joomla root with <Directory /path/to/Dolphine_home>), .htaccess and in my fvirtualhost file  and in my pmphp pools php.ini (also with a try to reach mu subfolder) but.. no luck. 
So i went to #php to be mocked a little for using a filemanager and a lot of other things ofcource :) They told me this is IMPOSSIBLE.. 
First i refused to belive as i found some stackoverflow post that told me otherwise.. 
but as it did not work for me I, atlast,subcommed to search and replace with  the command 
"find -name '_.php' -exec sed -i'.backup' 's/<?/<?php/' {} +"  and after that 
"find -name '_.php' -exec sed -i'.backup' 's/<?/<?phpphp/' {} +"  
but that did not work and gave me a blank page so i went at last and enabled short tags for all my pool in my pools php.ini.  This did not change a thing but only made also my Joomla blank. 
So  i reverted to original tags and sudenly both Dolphine and Joomla worked 

So then after this struggle I logged in..   First to "Full" version. There files showed up fine but i missed all the funktions i have got used to in "Light". 
After selecting a file i found them but honestly i like "light" better, the Full has to much fat around the meat for my taste. But then the problem was that i did not find any "Light" link and also no Logout link. 
So after erasing my browser cockie i tried the "Light" version. Unfortunatly there was no files listed.. So i remembered that i had not configured the define('HOMEDIR', ROOT . '/..'); /  variable   So i did that.. ..to define('HOMEDIR', ROOT . '/var/www/dunkan/www/wowi');
That gave me that Dolphine tried to open /var/www/dunkan/www/wowi/boing/var/www/dunkan/www/wowi
probably because i run my pools chrooted.
so then i tried 
define('HOMEDIR', ROOT . '/'); and 
define('HOMEDIR', ROOT . '../');  to reach down to my pools root /var/www/dunkan/www/wowi 
and lastly back to orginal path 
This worked in the "Full" mode but still no files are listed in the "Light" version.. 
all files original exept config that has new user and password.

So now i Of Cource Wonder what wall to bang my head in to get a idea of what is going on really.
old version worked fine on other server.. maybe i should go back to that now when i have short tags on or look at some alternative like quiexplorer.
But as it is worlds best filemanager (specially i like the posible commandline)I tought to ask you for any ideas you might have..

**Comment by YuriyNasretdinov** [comment]
Wow, what a story :). Yeah, probably if you change the homedir setting, your paths could get crazy, although I am not sure about that :). You could check which directory you use as HOMEDIR by just echo'ing it and checking tgat it is a valid path (you might lack slashes).
The "full" version was actually never completed so I understand why you like "light" version better :). You probably just ruined all your php files by doing sed becase things like "<?=$a?>" must not be replaced as "<?php=$a?>" is syntax error in PHP.
So I suggest setting the correct directory in config, start a new session and try again with short_open_tag enabled. Everything should work fine, although I never even tried to use Doplhin.php with PHP version higher than 5.3 :)
